name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    runs-on: self-hosted
    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    timeout-minutes: 360
    steps:
      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # If the key has a passphrase:
          # ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Fix known_hosts for GitHub
        run: |
          mkdir -p /root/.ssh
          ssh-keygen -f /root/.ssh/known_hosts -R github.com || true
          ssh-keygen -f /root/.ssh/known_hosts -R ssh.github.com || true
          ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> /root/.ssh/known_hosts
          ssh-keyscan -t rsa,ecdsa,ed25519 ssh.github.com >> /root/.ssh/known_hosts || true
          chmod 644 /root/.ssh/known_hosts

      - name: Checkout repository (with submodules over SSH)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0

      - name: Run full test
        run: ./full-test.sh

      - name: Cleanup
        if: always()
        run: ssh-add -D